[project]
name = "ai-fashion-tagging"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.10"
dependencies = [
    "openai>=1.60.2",
    "pydantic>=2.10.6",
]
